name: Run Tests

on:
  push:
    branches: ["develop"]
  pull_request: 
    branches: ["develop"]

jobs:
  test:
    steps:
        - uses: actions/checkout@master

        - uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel

        - name: Build with dotnet
          run: dotnet build --configuration Release

        - name: Run unit tests
          run: dotnet test --no-build --configuration Release
