name: master

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Test master
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '3.1.x'

        - name: Build with dotnet
          run: dotnet build --configuration Release

        - name: Run unit tests
          run: dotnet test --no-build --configuration Release

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: oronar/kinobot
        tags: latest
        tag_with_sha: true
